apiVersion: apps/v1
kind: Deployment
metadata:
  name: diary-app-deployment
  labels:
    app: diary-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diary-app
  template:
    metadata:
      labels:
        app: diary-app
    spec:
      containers:
      - name: diary-app
        image: ahmed22976/daily-diary-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: MONGODB_URI
          value: "mongodb://admin:password123@mongodb-service:27017/dailydiary?authSource=admin"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: diary-app-service
spec:
  selector:
    app: diary-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer